package com.sample
 
import com.sample.DroolsTest.Message;
import com.sample.Televizor;
import com.sample.Enums.*;
 
rule "Cena za smart televizor"
no-loop
    when
        tv : Televizor( cena>20000, mojaCena : cena )
    then
        System.out.println( mojaCena );
        tv.setSmart(true);
        //tv.setStatus( Message.GOODBYE );
        update( tv );
end

rule "GoodBye"
no-loop 
    when
        tv : Televizor( nacinPrijema  == NacinPrijema.KABLOVSKA, mySmart : smart )
    then
        System.out.println(tv.getCena());
    	System.out.println(tv.getNacinPrijema());
    	System.out.println(tv.getPrijemKablovska());
    	System.out.println(tv.getSekundarniPrijem());
    	System.out.println(tv.getNoveMogucnosti());
    	System.out.println(tv.getInternet());
    	System.out.println(tv.getPozicija());
    	System.out.println(tv.getUdaljenostOdTV());
    	System.out.println(tv.getDodatniUredjaji());
    	System.out.println(mySmart);
end
