package com.televizor

import com.televizor.Televizor;
import com.televizor.Enums.*;

rule "Nema novca za smart televizor"
lock-on-active true
salience 10
    when
        tv : Televizor(cena<20000)
    then
        tv.setSmart(Smart.NE);
        System.out.println("TEST1");
        update( tv );
end

rule "Nema novca za smart televizor ali ima za semi smart"
lock-on-active true
salience 10
    when
        tv : Televizor(cena>=20000 && cena<30000)
    then
        tv.setSmart(Smart.SEMISMART);
        System.out.println("TEST2");
        update( tv );
end

rule "Ima novca za smart televizor"
lock-on-active true
salience 10
    when
        tv : Televizor(cena>=30000)
    then
        tv.setSmart(Smart.SMART);
        System.out.println("TEST3");
        update( tv );
end

rule "Ako nema internet, ne treba mu Smart ili Semi-smart televizor"
lock-on-active true
    when
        tv : Televizor(internet == Internet.NE)
    then
        tv.setSmart(Smart.NE);
        System.out.println("TEST4");
        update( tv );
end

rule "Dovoljan je analogni tjuner za kablovsku"
lock-on-active true
    when
        tv : Televizor(nacinPrijema == NacinPrijema.KABLOVSKA && (prijemKablovska == PrijemKablovska.SETTOPBOX || prijemKablovska == PrijemKablovska.ANALOGNA))
    then
		tv.setTuner(Tuner.ANALOGNI);
		System.out.println("TEST5");
		update( tv );
end

rule "Potreban je DVB C tjuner za kablovsku"
lock-on-active true
    when
        tv : Televizor(nacinPrijema == NacinPrijema.KABLOVSKA && (prijemKablovska == PrijemKablovska.CAMMODUL || (prijemKablovska == PrijemKablovska.ANALOGNA && noveMogucnosti == true)))
    then
		tv.setTuner(Tuner.DVB_C);
		System.out.println("TEST6");
		update( tv );
end

rule "Potreban je DVB T2 uz DVB C tjuner za kablovsku"
no-loop true
    when
        tv : Televizor(tuner != null && tuner == Tuner.DVB_C && sekundarniPrijem == true)
    then
		tv.setTuner(Tuner.DVB_T2_C);
		System.out.println("TEST7");
		update( tv );
end

rule "Dovoljan je analogni tjuner za satelitsku"
lock-on-active true
    when
        tv : Televizor(nacinPrijema == NacinPrijema.SATELITSKA && prijemSatelitska == PrijemSatelitska.PROVAJDER)
    then
		tv.setTuner(Tuner.ANALOGNI);
		System.out.println("TEST8");
		update( tv );
end

rule "Potreban je DVB T2 uz analogni tjuner za kablovsku ili satelitsku"
no-loop true
    when
        tv : Televizor(tuner != null && tuner == Tuner.ANALOGNI && sekundarniPrijem == true)
    then
		tv.setTuner(Tuner.DVB_T2);
		System.out.println("TEST9");
		update( tv );
end

rule "Potreban je DVB S2 tjuner za satelitsku"
lock-on-active true
    when
        tv : Televizor(nacinPrijema == NacinPrijema.SATELITSKA && prijemSatelitska == PrijemSatelitska.SLOBODNO)
    then
		tv.setTuner(Tuner.DVB_S2);
		System.out.println("TEST10");
		update( tv );
end

rule "Potreban je DVB T2 uz DVB S2 tjuner za satelitsku"
no-loop true
    when
        tv : Televizor(tuner != null && tuner == Tuner.DVB_S2 && sekundarniPrijem == true)
    then
		tv.setTuner(Tuner.DVB_T2_S2);
		System.out.println("TEST11");
		update( tv );
end

rule "Ako je televizor Smart, barem ima DVB-T2 tjuner"
no-loop true
    when
        tv : Televizor(tuner != null && tuner == Tuner.ANALOGNI && smart != Smart.NE)
    then
        tv.setTuner(Tuner.DVB_T2);
        System.out.println("TEST12");
        update( tv );
end
/*
rule "Potreban je DVB T2 za zemaljsku"
no-loop true
    when
        tv : Televizor(nacinPrijema == NacinPrijema.ZEMALJSKA && mestoStanovanja == MestoStanovanja.GRADSKO, komentarTV : komentar)
    then
		tv.setTuner(Tuner.DVB_T2);
		tv.setKomentar(komentarTV + " ");
		update( tv );
end
*/
rule "Cena za Gradsko podruèje"
lock-on-active true
    when
        tv : Televizor(nacinPrijema == NacinPrijema.ZEMALJSKA && mestoStanovanja == MestoStanovanja.GRADSKO, komentarTV : komentar)
    then
		tv.setTuner(Tuner.DVB_T2);
		System.out.println("TEST13");
		tv.setKomentar(komentarTV + "Dovoljan je televizor sa DVB-T2 tjunerom.\n");
		update( tv );
end

rule "Cena za Prigradsko podruèje"
lock-on-active true
    when
        tv : Televizor(nacinPrijema == NacinPrijema.ZEMALJSKA && mestoStanovanja == MestoStanovanja.PRIGRADSKO && cena>=30000, komentarTV : komentar)
    then
		tv.setTuner(Tuner.DVB_T2);
		System.out.println("TEST14");
		tv.setKomentar(komentarTV + "Dovoljan je televizor sa DVB-T2 tjunerom.\n");
		update( tv );
end

rule "Neodgovarajuæa cena za Prigradsko podruèje"
lock-on-active true
    when
        tv : Televizor(nacinPrijema == NacinPrijema.ZEMALJSKA && mestoStanovanja == MestoStanovanja.PRIGRADSKO && cena<30000, komentarTV : komentar)
    then
		tv.setTuner(Tuner.DVB_T2);
		System.out.println("TEST15");
		tv.setKomentar(komentarTV + "Dovoljan je televizor sa DVB-T2 tjunerom.\nAli je preporuèljivo da odvojite više novca i kupite televizor sa kvalitetnijim tjunerom.\n");
		update( tv );
end

rule "Cena za Seosko podruèje"
lock-on-active true
    when
        tv : Televizor(nacinPrijema == NacinPrijema.ZEMALJSKA && mestoStanovanja == MestoStanovanja.SEOSKO && cena>=55000, komentarTV : komentar)
    then
		tv.setTuner(Tuner.DVB_T2);
		System.out.println("TEST16");
		tv.setKomentar(komentarTV + "Dovoljan je televizor sa DVB-T2 tjunerom.\n");
		update( tv );
end

rule "Neodgovarajuæa cena za Seosko podruèje"
lock-on-active true
    when
        tv : Televizor(nacinPrijema == NacinPrijema.ZEMALJSKA && mestoStanovanja == MestoStanovanja.SEOSKO && cena<55000, komentarTV : komentar)
    then
		tv.setTuner(Tuner.DVB_T2);
		System.out.println("TEST17");
		tv.setKomentar(komentarTV + "Dovoljan je televizor sa DVB-T2 tjunerom.\nAli je preporuèljivo da odvojite više novca i kupite televizor sa kvalitetnijim tjunerom.\n");
		update( tv );
end

rule "Broj portova"
lock-on-active true
    when
        tv : Televizor(dodUr : dodatniUredjaji)
    then
		String[] uredj = dodUr.split(" ");
		tv.setBrojPortova((uredj.length/2)+1);
		System.out.println("TEST18");
		update( tv );
end

rule "Broj portova sa settopboxom"
lock-on-active true
    when
        tv : Televizor((nacinPrijema == NacinPrijema.KABLOVSKA && prijemKablovska == PrijemKablovska.SETTOPBOX)||(nacinPrijema == NacinPrijema.SATELITSKA && prijemSatelitska == PrijemSatelitska.PROVAJDER), brPortova : brojPortova)
    then
		tv.setBrojPortova(brPortova+1);
		System.out.println("TEST19");
		update( tv );
end

rule "Ekran naspram prozora, nema dovoljno novca"
lock-on-active true
    when
        tv : Televizor(pozicija == Pozicija.NASPRAM && cena<170000, ekran : tipEkrana)
    then
		tv.setTipEkrana(TipEkrana.LED);
		System.out.println("TEST20");
		update( tv );
end

rule "Ekran naspram prozora, ima dovoljno novca"
lock-on-active true
    when
        tv : Televizor(pozicija == Pozicija.NASPRAM && cena>=200000, ekran : tipEkrana)
    then
		tv.setTipEkrana(TipEkrana.QLED);
		System.out.println("TEST21");
		update( tv );
end

rule "Ekran ispred prozora ili sa strane, nema dovoljno novca"
lock-on-active true
    when
        tv : Televizor((pozicija == Pozicija.ISPRED || pozicija == Pozicija.PORED) && cena<170000, ekran : tipEkrana)
    then
		tv.setTipEkrana(TipEkrana.LED);
		System.out.println("TEST22");
		update( tv );
end

rule "Ekran ispred prozora ili sa strane, ima nešto više novca"
lock-on-active true
    when
        tv : Televizor((pozicija == Pozicija.ISPRED || pozicija == Pozicija.PORED) && (cena>=170000 && cena<200000), ekran : tipEkrana)
    then
		tv.setTipEkrana(TipEkrana.OLED);
		System.out.println("TEST23");
		update( tv );
end

rule "Ekran ispred prozora ili sa strane, ima dovoljno novca"
lock-on-active true
    when
        tv : Televizor((pozicija == Pozicija.ISPRED || pozicija == Pozicija.PORED) && cena==200000, ekran : tipEkrana)
    then
		tv.setTipEkrana(TipEkrana.QLED);
		System.out.println("TEST24");
		update( tv );
end

rule "Ne postoji televizor koji nije Smart sa QLED ili OLED ekranom"
no-loop true
    when
        tv : Televizor(smart != null && smart != Smart.SMART && tipEkrana != null && tipEkrana != TipEkrana.LED, ekran : tipEkrana)
    then
		tv.setTipEkrana(TipEkrana.LED);
		System.out.println("TEST25");
		update( tv );
end

/*rule "Ekran ispred prozora ili sa strane, ima dovoljno novca"
lock-on-active true
    when
        tv : Televizor((pozicija == Pozicija.ISPRED || pozicija == Pozicija.PORED) && cena>=700000, ekran : tipEkrana)
    then
		tv.setTipEkrana(TipEkrana.QLED);
		update( tv );
end*/

rule "Dijagonala ekrana u zavisnosti od udaljenosti"
lock-on-active true
    when
        tv : Televizor(udaljenostOdTV != null, udaljenost : udaljenostOdTV)
    then
		tv.setDijagonala((int)(udaljenost*11.351));
		System.out.println("TEST26");
		update( tv );
end

rule "Ne postoji televizor sa dijagonalom manjom od 19 inèa"
lock-on-active true
    when
        tv : Televizor(dijagonala<19)
    then
		tv.setDijagonala(19);
		System.out.println("TEST27");
		update( tv );
end

rule "Štetno je gledati televizor na udaljenosti manjoj od 1m"
lock-on-active true
    when
        tv : Televizor(udaljenostOdTV < 1.0, kom : komentar)
    then
		tv.setDijagonala(0);
		tv.setKomentar(kom + "Na ovako maloj udaljenosti od ekrana je štetno gledati televiziju.\nZato se preporuèuje portabl televizor.\n");
		System.out.println("TEST28");
		update( tv );
end

rule "Za ekran manji od 32 inèa dovoljna je HD (HDReady) rezolucija"
no-loop true
    when
        tv : Televizor(dijagonala<32)
    then
		tv.setRezolucija(Rezolucija.HD);
		System.out.println("TEST29");
		update( tv );
end

rule "Za ekran veæi od 32 inèa potrebna je FullHD rezolucija"
no-loop true
    when
        tv : Televizor(dijagonala>=32)
    then
		tv.setRezolucija(Rezolucija.FULLHD);
		System.out.println("TEST30");
		update( tv );
end